[program:cs-skins-horizon]
process_name=%(program_name)s
command=php /mnt/nvme/www/html/cs-skins.local/artisan horizon
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/mnt/nvme/www/html/cs-skins.local/storage/logs/horizon.log
stopwaitsecs=3600