[program:cs_skins_reverb]
process_name=%(program_name)s
command=php /mnt/nvme/www/html/cs-skins.local/artisan reverb:start --host=0.0.0.0 --port=6001
directory=/mnt/nvme/www/html/cs-skins.local
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/cs_skins_reverb.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
stopwaitsecs=3600