[program:cs_skins_scheduler]
process_name=%(program_name)s
command=php /mnt/nvme/www/html/cs-skins.local/artisan schedule:work
directory=/mnt/nvme/www/html/cs-skins.local
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/mnt/nvme/www/html/cs-skins.local/storage/logs/scheduler.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
stopwaitsecs=30